sim.ngspice:
  extension: ".spice"
  comment_prefix: "*"
  templates:
    __subckt_header__: |-
      * ===============================================
      * {name}
      * {file_id}
      * ===============================================
      .subckt {name} {ports}
    __subckt_footer__: | 
      .ends {name}
    __subckt_call__: |- 
      X_{name} {ports} {ref}
    __netlist_header__: ""
    __netlist_footer__: |
      .end

sim.spectre:
  extension: ".scs"
  comment_prefix: "//"
  templates:
    __subckt_header__: |- 
      // ===============================================
      // {name}
      // {file_id}
      // ===============================================
      subckt {name} ({ports})
    __subckt_footer__: |
      ends
    __subckt_call__: |-
      {name} ({ports}) {ref}
    __netlist_header__: |
      simulator lang=spectre
      global 0
    __netlist_footer__: ""
    
lvs.klayout:
  extension: ".lvs.spice"
  comment_prefix: "*"
  templates:
    __subckt_header__: |-
      * ===============================================
      subckt {name} {ports}
    __subckt_footer__: |-
      ends
    __subckt_call__: |-
      X_{name} {ports} {ref}
    __netlist_header__: ""
    __netlist_footer__: ""
